version: "3.8"
services:
  web:
    build: .
    command: >
      bash -c "bundle exec rake db:migrate &&
      bundle exec rackup -o '0.0.0.0' -p 4567"
    ports:
      - "4567:4567"
    depends_on:
      - db
    environment:
      - HOST=http://localhost:3000
      - DB_HOST=db
      - DB_NAME=green_atom
      - DB_USER=postgres
      - DB_PASS=password
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=green_atom
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
